
map<uint8_t, function<void(Assembly &)>> Assembly::opcodeMap = {
    {0x00, [](Assembly &assembly)
     { assembly.brkHandler(); }},
    {0x01, [](Assembly &assembly)
     { assembly.oraIzxHandler(); }},
    {0x02, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x03, [](Assembly &assembly)
     { assembly.sloIzxHandler(); }},
    {0x04, [](Assembly &assembly)
     { assembly.nopZpHandler(); }},
    {0x05, [](Assembly &assembly)
     { assembly.oraZpHandler(); }},
    {0x06, [](Assembly &assembly)
     { assembly.aslZpHandler(); }},
    {0x07, [](Assembly &assembly)
     { assembly.sloZpHandler(); }},
    {0x08, [](Assembly &assembly)
     { assembly.phpHandler(); }},
    {0x09, [](Assembly &assembly)
     { assembly.oraImmHandler(); }},
    {0x0A, [](Assembly &assembly)
     { assembly.aslAHandler(); }},
    {0x0B, [](Assembly &assembly)
     { assembly.ancImmHandler(); }},
    {0x0C, [](Assembly &assembly)
     { assembly.nopAbsHandler(); }},
    {0x0D, [](Assembly &assembly)
     { assembly.oraAbsHandler(); }},
    {0x0E, [](Assembly &assembly)
     { assembly.aslAbsHandler(); }},
    {0x0F, [](Assembly &assembly)
     { assembly.sloAbsHandler(); }},
    {0x10, [](Assembly &assembly)
     { assembly.bplHandler(); }},
    {0x11, [](Assembly &assembly)
     { assembly.oraIzyHandler(); }},
    {0x12, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x13, [](Assembly &assembly)
     { assembly.sloIzyHandler(); }},
    {0x14, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0x15, [](Assembly &assembly)
     { assembly.oraZpxHandler(); }},
    {0x16, [](Assembly &assembly)
     { assembly.aslZpxHandler(); }},
    {0x17, [](Assembly &assembly)
     { assembly.sloZpxHandler(); }},
    {0x18, [](Assembly &assembly)
     { assembly.secHandler(); }},
    {0x19, [](Assembly &assembly)
     { assembly.oraAbyHandler(); }},
    {0x1A, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0x1B, [](Assembly &assembly)
     { assembly.sloAbyHandler(); }},
    {0x1C, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0x1D, [](Assembly &assembly)
     { assembly.oraAbxHandler(); }},
    {0x1E, [](Assembly &assembly)
     { assembly.aslAbxHandler(); }},
    {0x1F, [](Assembly &assembly)
     { assembly.sloAbxHandler(); }},
    {0x20, [](Assembly &assembly)
     { assembly.jsrAbsHandler(); }},
    {0x21, [](Assembly &assembly)
     { assembly.andIzxHandler(); }},
    {0x22, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x23, [](Assembly &assembly)
     { assembly.rlaIzxHandler(); }},
    {0x24, [](Assembly &assembly)
     { assembly.bitZpHandler(); }},
    {0x25, [](Assembly &assembly)
     { assembly.andZpHandler(); }},
    {0x26, [](Assembly &assembly)
     { assembly.rolZpHandler(); }},
    {0x27, [](Assembly &assembly)
     { assembly.rlaZpHandler(); }},
    {0x28, [](Assembly &assembly)
     { assembly.plpHandler(); }},
    {0x29, [](Assembly &assembly)
     { assembly.andImmHandler(); }},
    {0x2A, [](Assembly &assembly)
     { assembly.rolAHandler(); }},
    {0x2B, [](Assembly &assembly)
     { assembly.ancImmHandler(); }},
    {0x2C, [](Assembly &assembly)
     { assembly.bitAbsHandler(); }},
    {0x2D, [](Assembly &assembly)
     { assembly.andAbsHandler(); }},
    {0x2E, [](Assembly &assembly)
     { assembly.rolAbsHandler(); }},
    {0x2F, [](Assembly &assembly)
     { assembly.rlaAbsHandler(); }},
    {0x30, [](Assembly &assembly)
     { assembly.bmiRelHandler(); }},
    {0x31, [](Assembly &assembly)
     { assembly.andIzyHandler(); }},
    {0x32, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x33, [](Assembly &assembly)
     { assembly.rlaIzyHandler(); }},
    {0x34, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0x35, [](Assembly &assembly)
     { assembly.andZpxHandler(); }},
    {0x36, [](Assembly &assembly)
     { assembly.rolZpxHandler(); }},
    {0x37, [](Assembly &assembly)
     { assembly.rlaZpxHandler(); }},
    {0x38, [](Assembly &assembly)
     { assembly.secHandler(); }},
    {0x39, [](Assembly &assembly)
     { assembly.andAbyHandler(); }},
    {0x3A, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0x3B, [](Assembly &assembly)
     { assembly.rlaAbyHandler(); }},
    {0x3C, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0x3D, [](Assembly &assembly)
     { assembly.andAbxHandler(); }},
    {0x3E, [](Assembly &assembly)
     { assembly.rolAbxHandler(); }},
    {0x3F, [](Assembly &assembly)
     { assembly.rlaAbxHandler(); }},
    {0x40, [](Assembly &assembly)
     { assembly.rtiHandler(); }},
    {0x41, [](Assembly &assembly)
     { assembly.eorIzxHandler(); }},
    {0x42, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x43, [](Assembly &assembly)
     { assembly.sreIzxHandler(); }},
    {0x44, [](Assembly &assembly)
     { assembly.nopZpHandler(); }},
    {0x45, [](Assembly &assembly)
     { assembly.eorZpHandler(); }},
    {0x46, [](Assembly &assembly)
     { assembly.lsrZpHandler(); }},
    {0x47, [](Assembly &assembly)
     { assembly.sreZpHandler(); }},
    {0x48, [](Assembly &assembly)
     { assembly.phaHandler(); }},
    {0x49, [](Assembly &assembly)
     { assembly.eorImmHandler(); }},
    {0x4A, [](Assembly &assembly)
     { assembly.lsrHandler(); }},
    {0x4B, [](Assembly &assembly)
     { assembly.alrHandler(); }},
    {0x4C, [](Assembly &assembly)
     { assembly.jmpAbsHandler(); }},
    {0x4D, [](Assembly &assembly)
     { assembly.eorAbsHandler(); }},
    {0x4E, [](Assembly &assembly)
     { assembly.lsrAbsHandler(); }},
    {0x4F, [](Assembly &assembly)
     { assembly.sreAbsHandler(); }},
    {0x50, [](Assembly &assembly)
     { assembly.bvcRelHandler(); }},
    {0x51, [](Assembly &assembly)
     { assembly.eorIzyHandler(); }},
    {0x52, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x53, [](Assembly &assembly)
     { assembly.sreIzyHandler(); }},
    {0x54, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0x55, [](Assembly &assembly)
     { assembly.eorZpxHandler(); }},
    {0x56, [](Assembly &assembly)
     { assembly.lsrZpxHandler(); }},
    {0x57, [](Assembly &assembly)
     { assembly.sreZpxHandler(); }},
    {0x58, [](Assembly &assembly)
     { assembly.cliHandler(); }},
    {0x59, [](Assembly &assembly)
     { assembly.eorAbyHandler(); }},
    {0x5A, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0x5B, [](Assembly &assembly)
     { assembly.sreAbyHandler(); }},
    {0x5C, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0x5D, [](Assembly &assembly)
     { assembly.eorAbxHandler(); }},
    {0x5E, [](Assembly &assembly)
     { assembly.lsrAbxHandler(); }},
    {0x5F, [](Assembly &assembly)
     { assembly.sreAbxHandler(); }},
    {0x60, [](Assembly &assembly)
     { assembly.rtsHandler(); }},
    {0x61, [](Assembly &assembly)
     { assembly.adcIzxHandler(); }},
    {0x62, [](Assembly &assembly)
     { assembly.kilHandler(); }},
    {0x63, [](Assembly &assembly)
     { assembly.rraIzxHandler(); }},
    {0x64, [](Assembly &assembly)
     { assembly.nopZpHandler(); }},
    {0x65, [](Assembly &assembly)
     { assembly.adcZpHandler(); }},
    {0x66, [](Assembly &assembly)
     { assembly.rorZpHandler(); }},
    {0x67, [](Assembly &assembly)
     { assembly.rraZpHandler(); }},
    {0x68, [](Assembly &assembly)
     { assembly.plaHandler(); }},
    {0x69, [](Assembly &assembly)
     { assembly.adcImmHandler(); }},
    {0x6A, [](Assembly &assembly)
     { assembly.rorHandler(); }},
    {0x6B, [](Assembly &assembly)
     { assembly.arrHandler(); }},
    {0x6C, [](Assembly &assembly)
     { assembly.jmpIndHandler(); }},
    {0x6D, [](Assembly &assembly)
     { assembly.adcAbsHandler(); }},
    {0x6E, [](Assembly &assembly)
     { assembly.rorAbsHandler(); }},
    {0x6F, [](Assembly &assembly)
     { assembly.rraAbsHandler(); }},
    {0x80, [](Assembly &assembly)
     { assembly.nopImmHandler(); }},
    {0x81, [](Assembly &assembly)
     { assembly.staIzxHandler(); }},
    {0x82, [](Assembly &assembly)
     { assembly.nopImmHandler(); }},
    {0x83, [](Assembly &assembly)
     { assembly.saxIzxHandler(); }},
    {0x84, [](Assembly &assembly)
     { assembly.styZpHandler(); }},
    {0x85, [](Assembly &assembly)
     { assembly.staZpHandler(); }},
    {0x86, [](Assembly &assembly)
     { assembly.stxZpHandler(); }},
    {0x87, [](Assembly &assembly)
     { assembly.saxZpHandler(); }},
    {0x88, [](Assembly &assembly)
     { assembly.deyHandler(); }},
    {0x89, [](Assembly &assembly)
     { assembly.nopImmHandler(); }},
    {0x8A, [](Assembly &assembly)
     { assembly.txaHandler(); }},
    {0x8B, [](Assembly &assembly)
     { assembly.xaaImmHandler(); }},
    {0x8C, [](Assembly &assembly)
     { assembly.styAbsHandler(); }},
    {0x8D, [](Assembly &assembly)
     { assembly.staAbsHandler(); }},
    {0x8E, [](Assembly &assembly)
     { assembly.stxAbsHandler(); }},
    {0x8F, [](Assembly &assembly)
     { assembly.saxAbsHandler(); }},
    {0x70, [](Assembly &assembly)
     { assembly.bvsHandler(); }},
    {0x71, [](Assembly &assembly)
     { assembly.adcIzxHandler(); }},
    {0x72, [](Assembly &assembly)
     { assembly.crashHandler(); }},
    {0x73, [](Assembly &assembly)
     { assembly.rraIzxHandler(); }},
    {0x74, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0x75, [](Assembly &assembly)
     { assembly.adcZpxHandler(); }},
    {0x76, [](Assembly &assembly)
     { assembly.rorZpxHandler(); }},
    {0x77, [](Assembly &assembly)
     { assembly.rraZpxHandler(); }},
    {0x78, [](Assembly &assembly)
     { assembly.seiHandler(); }},
    {0x79, [](Assembly &assembly)
     { assembly.adcAbyHandler(); }},
    {0x7A, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0x7B, [](Assembly &assembly)
     { assembly.rraAbyHandler(); }},
    {0x7C, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0x7D, [](Assembly &assembly)
     { assembly.adcAbxHandler(); }},
    {0x7E, [](Assembly &assembly)
     { assembly.rorAbxHandler(); }},
    {0x7F, [](Assembly &assembly)
     { assembly.rraAbxHandler(); }},
    {0x90, [](Assembly &assembly)
     { assembly.bccHandler(); }},
    {0x91, [](Assembly &assembly)
     { assembly.staIzyHandler(); }},
    {0x92, [](Assembly &assembly)
     { assembly.crashHandler(); }},
    {0x93, [](Assembly &assembly)
     { assembly.ahxIzyHandler(); }},
    {0x94, [](Assembly &assembly)
     { assembly.styZpxHandler(); }},
    {0x95, [](Assembly &assembly)
     { assembly.staZpxHandler(); }},
    {0x96, [](Assembly &assembly)
     { assembly.stxZpyHandler(); }},
    {0x97, [](Assembly &assembly)
     { assembly.saxZpyHandler(); }},
    {0x98, [](Assembly &assembly)
     { assembly.tyaHandler(); }},
    {0x99, [](Assembly &assembly)
     { assembly.staAbyHandler(); }},
    {0x9A, [](Assembly &assembly)
     { assembly.txsHandler(); }},
    {0x9B, [](Assembly &assembly)
     { assembly.tasAbyHandler(); }},
    {0x9C, [](Assembly &assembly)
     { assembly.shyAbxHandler(); }},
    {0x9D, [](Assembly &assembly)
     { assembly.staAbxHandler(); }},
    {0x9E, [](Assembly &assembly)
     { assembly.shxAbyHandler(); }},
    {0x9F, [](Assembly &assembly)
     { assembly.ahxAbyHandler(); }},
    {0xA0, [](Assembly &assembly)
     { assembly.ldyImmHandler(); }},
    {0xA1, [](Assembly &assembly)
     { assembly.ldaIzxHandler(); }},
    {0xA2, [](Assembly &assembly)
     { assembly.ldxImmHandler(); }},
    {0xA3, [](Assembly &assembly)
     { assembly.laxIzxHandler(); }},
    {0xA4, [](Assembly &assembly)
     { assembly.ldyZpHandler(); }},
    {0xA5, [](Assembly &assembly)
     { assembly.ldaZpHandler(); }},
    {0xA6, [](Assembly &assembly)
     { assembly.ldxZpHandler(); }},
    {0xA7, [](Assembly &assembly)
     { assembly.laxZpHandler(); }},
    {0xA8, [](Assembly &assembly)
     { assembly.tayHandler(); }},
    {0xA9, [](Assembly &assembly)
     { assembly.ldaImmHandler(); }},
    {0xAA, [](Assembly &assembly)
     { assembly.taxHandler(); }},
    {0xAB, [](Assembly &assembly)
     { assembly.laxImmHandler(); }},
    {0xAC, [](Assembly &assembly)
     { assembly.ldyAbsHandler(); }},
    {0xAD, [](Assembly &assembly)
     { assembly.ldaAbsHandler(); }},
    {0xAE, [](Assembly &assembly)
     { assembly.ldxAbsHandler(); }},
    {0xAF, [](Assembly &assembly)
     { assembly.laxAbsHandler(); }},
    {0xB0, [](Assembly &assembly)
     { assembly.bcsHandler(); }},
    {0xB1, [](Assembly &assembly)
     { assembly.ldaIzyHandler(); }},
    {0xB2, [](Assembly &assembly)
     { assembly.crashHandler(); }},
    {0xB3, [](Assembly &assembly)
     { assembly.laxIzyHandler(); }},
    {0xB4, [](Assembly &assembly)
     { assembly.ldyZpxHandler(); }},
    {0xB5, [](Assembly &assembly)
     { assembly.ldaZpxHandler(); }},
    {0xB6, [](Assembly &assembly)
     { assembly.ldxZpyHandler(); }},
    {0xB7, [](Assembly &assembly)
     { assembly.laxZpyHandler(); }},
    {0xB8, [](Assembly &assembly)
     { assembly.clvHandler(); }},
    {0xB9, [](Assembly &assembly)
     { assembly.ldaAbyHandler(); }},
    {0xBA, [](Assembly &assembly)
     { assembly.tsxHandler(); }},
    {0xBB, [](Assembly &assembly)
     { assembly.lasAbyHandler(); }},
    {0xBC, [](Assembly &assembly)
     { assembly.ldyAbxHandler(); }},
    {0xBD, [](Assembly &assembly)
     { assembly.ldaAbxHandler(); }},
    {0xBE, [](Assembly &assembly)
     { assembly.ldxAbyHandler(); }},
    {0xBF, [](Assembly &assembly)
     { assembly.laxAbyHandler(); }},
    {0xC0, [](Assembly &assembly)
     { assembly.cpyImmHandler(); }},
    {0xC1, [](Assembly &assembly)
     { assembly.cmpIzxHandler(); }},
    {0xC2, [](Assembly &assembly)
     { assembly.nopImmHandler(); }},
    {0xC3, [](Assembly &assembly)
     { assembly.dcpIzxHandler(); }},
    {0xC4, [](Assembly &assembly)
     { assembly.cpyZpHandler(); }},
    {0xC5, [](Assembly &assembly)
     { assembly.cmpZpHandler(); }},
    {0xC6, [](Assembly &assembly)
     { assembly.decZpHandler(); }},
    {0xC7, [](Assembly &assembly)
     { assembly.dcpZpHandler(); }},
    {0xC8, [](Assembly &assembly)
     { assembly.inyHandler(); }},
    {0xC9, [](Assembly &assembly)
     { assembly.cmpImmHandler(); }},
    {0xCA, [](Assembly &assembly)
     { assembly.dexHandler(); }},
    {0xCB, [](Assembly &assembly)
     { assembly.axsImmHandler(); }},
    {0xCC, [](Assembly &assembly)
     { assembly.cpyAbsHandler(); }},
    {0xCD, [](Assembly &assembly)
     { assembly.cmpAbsHandler(); }},
    {0xCE, [](Assembly &assembly)
     { assembly.decAbsHandler(); }},
    {0xCF, [](Assembly &assembly)
     { assembly.dcpAbsHandler(); }},
    {0xD0, [](Assembly &assembly)
     { assembly.bneHandler(); }},
    {0xD1, [](Assembly &assembly)
     { assembly.cmpIzyHandler(); }},
    {0xD2, [](Assembly &assembly)
     { assembly.crashHandler(); }},
    {0xD3, [](Assembly &assembly)
     { assembly.dcpIzyHandler(); }},
    {0xD4, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0xD5, [](Assembly &assembly)
     { assembly.cmpZpxHandler(); }},
    {0xD6, [](Assembly &assembly)
     { assembly.decZpxHandler(); }},
    {0xD7, [](Assembly &assembly)
     { assembly.dcpZpxHandler(); }},
    {0xD8, [](Assembly &assembly)
     { assembly.cldHandler(); }},
    {0xD9, [](Assembly &assembly)
     { assembly.cmpAbyHandler(); }},
    {0xDA, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0xDB, [](Assembly &assembly)
     { assembly.dcpAbyHandler(); }},
    {0xDC, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0xDD, [](Assembly &assembly)
     { assembly.cmpAbxHandler(); }},
    {0xDE, [](Assembly &assembly)
     { assembly.decAbxHandler(); }},
    {0xDF, [](Assembly &assembly)
     { assembly.dcpAbxHandler(); }},
    {0xE0, [](Assembly &assembly)
     { assembly.cpxImmHandler(); }},
    {0xE1, [](Assembly &assembly)
     { assembly.sbcIzxHandler(); }},
    {0xE2, [](Assembly &assembly)
     { assembly.nopImmHandler(); }},
    {0xE3, [](Assembly &assembly)
     { assembly.iscIzxHandler(); }},
    {0xE4, [](Assembly &assembly)
     { assembly.cpxZpHandler(); }},
    {0xE5, [](Assembly &assembly)
     { assembly.sbcZpHandler(); }},
    {0xE6, [](Assembly &assembly)
     { assembly.incZpHandler(); }},
    {0xE7, [](Assembly &assembly)
     { assembly.iscZpHandler(); }},
    {0xE8, [](Assembly &assembly)
     { assembly.inxHandler(); }},
    {0xE9, [](Assembly &assembly)
     { assembly.sbcImmHandler(); }},
    {0xEA, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0xEB, [](Assembly &assembly)
     { assembly.sbcImmHandler(); }},
    {0xEC, [](Assembly &assembly)
     { assembly.cpxAbsHandler(); }},
    {0xED, [](Assembly &assembly)
     { assembly.sbcAbsHandler(); }},
    {0xEE, [](Assembly &assembly)
     { assembly.incAbsHandler(); }},
    {0xEF, [](Assembly &assembly)
     { assembly.iscAbsHandler(); }},
    {0xF0, [](Assembly &assembly)
     { assembly.beqHandler(); }},
    {0xF1, [](Assembly &assembly)
     { assembly.sbcIzyHandler(); }},
    {0xF2, [](Assembly &assembly)
     { assembly.crashHandler(); }},
    {0xF3, [](Assembly &assembly)
     { assembly.iscIzyHandler(); }},
    {0xF4, [](Assembly &assembly)
     { assembly.nopZpxHandler(); }},
    {0xF5, [](Assembly &assembly)
     { assembly.sbcZpxHandler(); }},
    {0xF6, [](Assembly &assembly)
     { assembly.incZpxHandler(); }},
    {0xF7, [](Assembly &assembly)
     { assembly.iscZpxHandler(); }},
    {0xF8, [](Assembly &assembly)
     { assembly.sedHandler(); }},
    {0xF9, [](Assembly &assembly)
     { assembly.sbcAbyHandler(); }},
    {0xFA, [](Assembly &assembly)
     { assembly.nopHandler(); }},
    {0xFB, [](Assembly &assembly)
     { assembly.iscAbyHandler(); }},
    {0xFC, [](Assembly &assembly)
     { assembly.nopAbxHandler(); }},
    {0xFD, [](Assembly &assembly)
     { assembly.sbcAbxHandler(); }},
    {0xFE, [](Assembly &assembly)
     { assembly.incAbxHandler(); }},
    {0xFF, [](Assembly &assembly)
     { assembly.iscAbxHandler(); }}};
